version: '3'

networks:
  laravel-sts:

services:
  nginx-sts:
    image: nginx:1.20.2-alpine
    container_name: nginx-sts
    ports:
      - "9080:80"
    volumes:
      - ./api-sts:/var/www
      - ./nginx/sts/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-sts
      - mysql-sts
    networks:
      - laravel-sts

  mysql-sts:
    image: mysql:5.7.22
    container_name: mysql-sts
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: sts
      MYSQL_USER: newuser
      MYSQL_PASSWORD: passwor434
      MYSQL_ROOT_PASSWORD: passwor434
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel-sts

  php-sts:
    build:
      context: .
      dockerfile: STS.Dockerfile
    container_name: php-sts
    volumes:
      - ./api-sts:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel-sts
